name: skillshark
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  flutter_brand_icons: ^1.1.0
  smart_grid_view: ^0.2.1 
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0+1"
  firebase_storage: "^7.0.0"
  github_sign_in: ^0.0.1
  image_picker_web: ^1.0.9
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  chewie: ^1.0.0
  video_player: ^2.1.0
  uuid: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
