name: skillshark
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_brand_icons: ^1.1.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0
  github_sign_in: ^0.0.1
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  chewie: ^1.0.0
  video_player: ^2.1.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_svg: ^0.22.0
  get: ^4.1.4
  flutter_feather_icons: ^2.0.0+1
  auto_size_text: ^2.1.0
  scroll_to_index: ^2.0.0
  csc_picker: ^0.2.5
  string_validator: ^0.3.0
  uuid: ^3.0.4
  file_picker: ^3.0.3
  markdown_editable_textinput: ^2.0.0
  flutter_colorpicker: ^0.3.5
  dotted_border: ^2.0.0
  flutter_conditional_rendering: ^2.0.0
  flick_video_player: ^0.3.0
  url_launcher: ^6.0.9
  markdowneditor: ^0.0.2
  flutter_markdown: ^0.5.2 # old version # TODO: Fix on change


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/cards/
