name: CI (simple)

on:
  push:
    branches:
      - master

jobs:
  flutter_test:
  name: Run flutter testing and analysis
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
